### ISSUE TITLE
npm test 실패

### ISSUE THREAD

**Issue by iolo** [fastcampus/stylelint-config#1]
클론후 `npm ci` 하고 `npm test`하면 실패합니다.

```
❯ git clone git@github.com:fastcampus/stylelint-config.git
...
❯ npm ci
...
❯ npm test

> @fastcampus/stylelint-config@0.0.2 test /Users/iolo/workspace/fastcampus/stylelint-config
> stylelint test.css --config index.js

Error: Cannot find module 'prettier'
Require stack:
- /Users/iolo/workspace/fastcampus/stylelint-config/node_modules/stylelint-prettier/stylelint-prettier.js
- /Users/iolo/workspace/fastcampus/stylelint-config/node_modules/stylelint/lib/augmentConfig.js
- /Users/iolo/workspace/fastcampus/stylelint-config/node_modules/stylelint/lib/createStylelint.js
- /Users/iolo/workspace/fastcampus/stylelint-config/node_modules/stylelint/lib/printConfig.js
- /Users/iolo/workspace/fastcampus/stylelint-config/node_modules/stylelint/lib/cli.js
- /Users/iolo/workspace/fastcampus/stylelint-config/node_modules/stylelint/bin/stylelint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/Users/iolo/workspace/fastcampus/stylelint-config/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at /Users/iolo/workspace/fastcampus/stylelint-config/node_modules/stylelint-prettier/stylelint-prettier.js:42:20
    at /Users/iolo/workspace/fastcampus/stylelint-config/node_modules/stylelint/lib/lintPostcssResult.js:118:8
    at Array.map (<anonymous>)
    at /Users/iolo/workspace/fastcampus/stylelint-config/node_modules/stylelint/lib/lintPostcssResult.js:110:18
    at Array.forEach (<anonymous>)
    at lintPostcssResult (/Users/iolo/workspace/fastcampus/stylelint-config/node_modules/stylelint/lib/lintPostcssResult.js:74:8)
npm ERR! Test failed.  See above for more details.

stylelint-config on  feature/github-actions [$?] is 📦 v0.0.2 via ⬢ v14.15.3 on ☁️ iolo@fastcampus.co.kr(asia-northeast3)
```

그래서 `prettier` 의존성을 추가하고 `npm test`했지만...

```console
❯ npm install prettier --save-dev
+ prettier@2.2.1
added 1 package from 1 contributor and audited 273 packages in 1.223s

54 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


stylelint-config on  feature/github-actions [$!?] is 📦 v0.0.2 via ⬢ v14.15.3 on ☁️ iolo@fastcampus.co.kr(asia-northeast3)
❯ npm test

> @fastcampus/stylelint-config@0.0.2 test /Users/iolo/workspace/fastcampus/stylelint-config
> stylelint test.css --config index.js


test.css
  4:1  ✖  Expected empty line before comment   comment-empty-line-before
  5:1  ✖  Expected empty line before comment   comment-empty-line-before
  6:1  ✖  Expected empty line before comment   comment-empty-line-before
 13:1  ✖  Expected empty line before comment   comment-empty-line-before
 14:1  ✖  Expected empty line before comment   comment-empty-line-before
 17:1  ✖  Expected empty line before comment   comment-empty-line-before
 18:1  ✖  Expected empty line before comment   comment-empty-line-before
 21:1  ✖  Expected empty line before comment   comment-empty-line-before
 22:1  ✖  Expected empty line before comment   comment-empty-line-before

npm ERR! Test failed.  See above for more details.

stylelint-config on  feature/github-actions [$!?] is 📦 v0.0.2 via ⬢ v14.15.3 on ☁️ iolo@fastcampus.co.kr(asia-northeast3)
❯
```
이번엔 테스트 픽스쳐(test.css) 오류로 테스트가 실패합니다.
의도한 오류일까요?

**Comment by jaewon-noh** [comment]
테스트 성공하도록 수정하여 pr올리겠습니다.

**Comment by jaewon-noh** [comment]
관련 pr이 병합 되었습니다. 
이슈 닫도록 하겠습니다.
